spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql-username}
    password: ${mysql-password}
    url: jdbc:mysql://${mysql-host}:${mysql-port}/${mysql-database}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=false
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
